diary 2018-10-19-log.txt;
disp('Continuous Case:');
disp('Configuration:');
disp('pho = 0.1');
disp('diff_thresold = 1e-5');
disp('train_error_threshold = 1e-5');
tic;
run_continuous;
toc;
disp('Binary Case:');
disp('Configuration:');
disp('pho = 0.1');
disp('diff_thresold = 1e-5');
disp('auc_threshold = 1e-5');
tic;
run_binary;
save result-2018-10-19;
toc;
diary off;